import { MetaDataUploadJson } from "../model/metadatauploadjson";

export const dummyData: MetaDataUploadJson = {
    jobId: '',
    createInitialMetadataJobId: '',
    fileConversionJobId: '',
    processingFinished: false,
    dataFilesIDs: null,
    metadataJson: [
      {
        identID: '111',
        counter: 0,
        sourcename: 'biogas sample 1',
        spectrumFile: 'sample1.mgf',
        psmFile: 'sample1.csv',
        group: 'MdOA',
        projectIdentifier: 'ISAS_SDRF',
        project: '',
        study: '',
        program: '',
        biologicalReplicate: 1,
        metagenomes: 'ecological metagenome',
        ecologicalMetagenomes: 'biogas metagenom',
        syntheticMetagenome: '/',
        organismalMetagenomes: 'human gut metagenom',
        analyticalFraction: '',
        temperatureCondtions: '',
        pressure: '',
        pH: '',
        carbonSource: '',
        electronSource: '',
        countIdentifiedSpezies: '',
        assayName: 'Assay 1',
        experimentType: 'heat shock',
        technologyType: '',
        technicalReplicate: 1,
        label: 'label 1',
        fractionIdentifier: 1,
        cleavantAgentDetails: '',
        instrument: '',
        modificationParameters: '',
        modificationParameters1: '',
        modificationParameters2: '',
        dissociationMethod: '',
        precursorMassTolerance: '',
        fragmentMassTolerance: '',
        dataFile: 'datafile path 1',
        fileUri: 'file uri 1',
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        comment: '',
        factorValue: 'heat shock',
        fileType: 'mgf1',
      },
      {
        identID: '222',
        counter: 1,
        sourcename: 'biogas sample 2',
        spectrumFile: 'sample1.mgf',
        psmFile: 'sample1.csv',
        group: 'MdOA',
        projectIdentifier: 'ISAS_SDRF',
        project: '',
        study: '',
        program: '',
        biologicalReplicate: 1,
        metagenomes: 'ecological metagenome',
        ecologicalMetagenomes: 'biogas metagenom',
        syntheticMetagenome: '/',
        organismalMetagenomes: 'human gut metagenom',
        analyticalFraction: '',
        temperatureCondtions: '',
        pressure: '',
        pH: '',
        carbonSource: '',
        electronSource: '',
        countIdentifiedSpezies: '',
        assayName: 'Assay 1',
        experimentType: 'heat shock',
        technologyType: '',
        technicalReplicate: 1,
        label: 'label 1',
        fractionIdentifier: 1,
        cleavantAgentDetails: '',
        instrument: '',
        modificationParameters: '',
        modificationParameters1: '',
        modificationParameters2: '',
        dissociationMethod: '',
        precursorMassTolerance: '',
        fragmentMassTolerance: '',
        dataFile: 'datafile path 1',
        fileUri: 'file uri 1',
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        comment: '',
        factorValue: 'heat shock',
        fileType: 'mgf2',
      },
      {
        identID: '333',
        counter: 2,
        sourcename: 'biogas sample 3',
        spectrumFile: 'sample1.mgf',
        psmFile: 'sample1.csv',
        group: 'MdOA',
        projectIdentifier: 'ISAS_SDRF',
        project: '',
        study: '',
        program: '',
        biologicalReplicate: 1,
        metagenomes: 'ecological metagenome',
        ecologicalMetagenomes: 'biogas metagenom',
        syntheticMetagenome: '/',
        organismalMetagenomes: 'human gut metagenom',
        analyticalFraction: '',
        temperatureCondtions: '',
        pressure: '',
        pH: '',
        carbonSource: '',
        electronSource: '',
        countIdentifiedSpezies: '',
        assayName: 'Assay 1',
        experimentType: 'heat shock',
        technologyType: '',
        technicalReplicate: 1,
        label: 'label 1',
        fractionIdentifier: 1,
        cleavantAgentDetails: '',
        instrument: '',
        modificationParameters: '',
        modificationParameters1: '',
        modificationParameters2: '',
        dissociationMethod: '',
        precursorMassTolerance: '',
        fragmentMassTolerance: '',
        dataFile: 'datafile path 1',
        fileUri: 'file uri 1',
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        comment: '',
        factorValue: 'heat shock',
        fileType: 'mgf3',
      },
    ],
  };
