import { MetaDataUploadJson } from "../model/metadatauploadjson";

export const dummyData: MetaDataUploadJson = {
    jobId: '',
    processingPipeline: 'metaproteomeanalyzer',
    createInitialMetadataJobId: '',
    fileConversionJobId: '',
    processingFinished: false,
    //dataFilesIDs: null,
    metadataJson: [
      {
        identID: '111',
        counter: 0,
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        spectrumFile: 'sample1.mgf',
        psmFile: 'PSM_sample1.csv',
        peptideFile: 'PEPTIDE_sample1.csv',
        ontId2Enabled: new Map<string, boolean>(
          [
            ['sourcename', true],
            ['group', true],
            ['projectIdentifier', true],
            ['project', true],
            ['study', true],
            ['program', true],
            ['biologicalReplicate', true],
            ['metagenomes', true],
            ['ecologicalMetagenomes', true],
            ['syntheticMetagenome', true],
            ['organismalMetagenomes', true],
            ['analyticalFraction', true],
            ['temperatureCondtions', true],
            ['pressure', true],
            ['pH', true],
            ['carbonSource', true],
            ['electronSource', true],
            ['countIdentifiedSpezies', true],
            ['assayName', true],
            ['experimentType', true],
            ['technologyType', true],
            ['technicalReplicate', true],
            ['label', true],
            ['fractionIdentifier', true],
            ['cleavantAgentDetails', true],
            ['instrument', true],
            ['modificationParameters', true],
            ['modificationParameters1', true],
            ['modificationParameters2', true],
            ['dissociationMethod', true],
            ['precursorMassTolerance', true],
            ['fragmentMassTolerance', true],
            ['dataFile', true],
            ['fileUri', true],
            ['comment', true],
            ['factorValue', true],
            ['fileType', true]
          ]
        ),
        ontId2Param: new Map<string, string>(
          [
            ['sourcename', 'biogas sample 1'],
            ['group', 'MdOA'],
            ['projectIdentifier', 'ISAS_SDRF'],
            ['project', ''],
            ['study', ''],
            ['program', ''],
            ['biologicalReplicate', '1'],
            ['metagenomes', 'ecological metagenome'],
            ['ecologicalMetagenomes', 'biogas metagenom'],
            ['syntheticMetagenome', '/'],
            ['organismalMetagenomes', 'human gut metagenom'],
            ['analyticalFraction', ''],
            ['temperatureCondtions', ''],
            ['pressure', ''],
            ['pH', ''],
            ['carbonSource', ''],
            ['electronSource', ''],
            ['countIdentifiedSpezies', ''],
            ['assayName', 'Assay 1'],
            ['experimentType', 'heat shock'],
            ['technologyType', ''],
            ['technicalReplicate', '1'],
            ['label', 'label 1'],
            ['fractionIdentifier', '1'],
            ['cleavantAgentDetails', ''],
            ['instrument', ''],
            ['modificationParameters', ''],
            ['modificationParameters1', ''],
            ['modificationParameters2', ''],
            ['dissociationMethod', ''],
            ['precursorMassTolerance', ''],
            ['fragmentMassTolerance', ''],
            ['dataFile', 'datafile path 1'],
            ['fileUri', 'file uri 1'],
            ['comment', ''],
            ['factorValue', 'heat shock'],
            ['fileType', 'mgf1']
          ]
        ),
      },
      {
        identID: '222',
        counter: 1,
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        spectrumFile: 'sample1.mgf',
        psmFile: 'PSM_sample1.csv',
        peptideFile: 'PEPTIDE_sample1.csv',
        ontId2Enabled: new Map<string, boolean>(
          [
            ['sourcename', true],
            ['group', true],
            ['projectIdentifier', true],
            ['project', true],
            ['study', true],
            ['program', true],
            ['biologicalReplicate', true],
            ['metagenomes', true],
            ['ecologicalMetagenomes', true],
            ['syntheticMetagenome', true],
            ['organismalMetagenomes', true],
            ['analyticalFraction', true],
            ['temperatureCondtions', true],
            ['pressure', true],
            ['pH', true],
            ['carbonSource', true],
            ['electronSource', true],
            ['countIdentifiedSpezies', true],
            ['assayName', true],
            ['experimentType', true],
            ['technologyType', true],
            ['technicalReplicate', true],
            ['label', true],
            ['fractionIdentifier', true],
            ['cleavantAgentDetails', true],
            ['instrument', true],
            ['modificationParameters', true],
            ['modificationParameters1', true],
            ['modificationParameters2', true],
            ['dissociationMethod', true],
            ['precursorMassTolerance', true],
            ['fragmentMassTolerance', true],
            ['dataFile', true],
            ['fileUri', true],
            ['comment', true],
            ['factorValue', true],
            ['fileType', true]
          ]
        ),
        ontId2Param: new Map<string, string>(
          [
            ['sourcename', 'biogas sample 1'],
            ['group', 'MdOA'],
            ['projectIdentifier', 'ISAS_SDRF'],
            ['project', ''],
            ['study', ''],
            ['program', ''],
            ['biologicalReplicate', '1'],
            ['metagenomes', 'ecological metagenome'],
            ['ecologicalMetagenomes', 'biogas metagenom'],
            ['syntheticMetagenome', '/'],
            ['organismalMetagenomes', 'human gut metagenom'],
            ['analyticalFraction', ''],
            ['temperatureCondtions', ''],
            ['pressure', ''],
            ['pH', ''],
            ['carbonSource', ''],
            ['electronSource', ''],
            ['countIdentifiedSpezies', ''],
            ['assayName', 'Assay 1'],
            ['experimentType', 'heat shock'],
            ['technologyType', ''],
            ['technicalReplicate', '1'],
            ['label', 'label 1'],
            ['fractionIdentifier', '1'],
            ['cleavantAgentDetails', ''],
            ['instrument', ''],
            ['modificationParameters', ''],
            ['modificationParameters1', ''],
            ['modificationParameters2', ''],
            ['dissociationMethod', ''],
            ['precursorMassTolerance', ''],
            ['fragmentMassTolerance', ''],
            ['dataFile', 'datafile path 1'],
            ['fileUri', 'file uri 1'],
            ['comment', ''],
            ['factorValue', 'heat shock'],
            ['fileType', 'mgf1']
          ]
        ),
      },
      {
        identID: '333',
        counter: 2,
        mzID: 'mzID 1',
        mzML: 'mzML 1',
        spectrumFile: 'sample1.mgf',
        psmFile: 'PSM_sample1.csv',
        peptideFile: 'PEPTIDE_sample1.csv',
        ontId2Enabled: new Map<string, boolean>(
          [
            ['sourcename', true],
            ['group', true],
            ['projectIdentifier', true],
            ['project', true],
            ['study', true],
            ['program', true],
            ['biologicalReplicate', true],
            ['metagenomes', true],
            ['ecologicalMetagenomes', true],
            ['syntheticMetagenome', true],
            ['organismalMetagenomes', true],
            ['analyticalFraction', true],
            ['temperatureCondtions', true],
            ['pressure', true],
            ['pH', true],
            ['carbonSource', true],
            ['electronSource', true],
            ['countIdentifiedSpezies', true],
            ['assayName', true],
            ['experimentType', true],
            ['technologyType', true],
            ['technicalReplicate', true],
            ['label', true],
            ['fractionIdentifier', true],
            ['cleavantAgentDetails', true],
            ['instrument', true],
            ['modificationParameters', true],
            ['modificationParameters1', true],
            ['modificationParameters2', true],
            ['dissociationMethod', true],
            ['precursorMassTolerance', true],
            ['fragmentMassTolerance', true],
            ['dataFile', true],
            ['fileUri', true],
            ['comment', true],
            ['factorValue', true],
            ['fileType', true]
          ]
        ),
        ontId2Param: new Map<string, string>(
          [
            ['sourcename', 'biogas sample 1'],
            ['group', 'MdOA'],
            ['projectIdentifier', 'ISAS_SDRF'],
            ['project', ''],
            ['study', ''],
            ['program', ''],
            ['biologicalReplicate', '1'],
            ['metagenomes', 'ecological metagenome'],
            ['ecologicalMetagenomes', 'biogas metagenom'],
            ['syntheticMetagenome', '/'],
            ['organismalMetagenomes', 'human gut metagenom'],
            ['analyticalFraction', ''],
            ['temperatureCondtions', ''],
            ['pressure', ''],
            ['pH', ''],
            ['carbonSource', ''],
            ['electronSource', ''],
            ['countIdentifiedSpezies', ''],
            ['assayName', 'Assay 1'],
            ['experimentType', 'heat shock'],
            ['technologyType', ''],
            ['technicalReplicate', '1'],
            ['label', 'label 1'],
            ['fractionIdentifier', '1'],
            ['cleavantAgentDetails', ''],
            ['instrument', ''],
            ['modificationParameters', ''],
            ['modificationParameters1', ''],
            ['modificationParameters2', ''],
            ['dissociationMethod', ''],
            ['precursorMassTolerance', ''],
            ['fragmentMassTolerance', ''],
            ['dataFile', 'datafile path 1'],
            ['fileUri', 'file uri 1'],
            ['comment', ''],
            ['factorValue', 'heat shock'],
            ['fileType', 'mgf1']
          ]
        ),
      },
    ],
  };
